default: &default
  adapter: postgresql
  database: indotaxeye_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: indotaxeye_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: indotaxeye_test
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: indotaxeye_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000